// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v7.36.0
// source: opossum.proto

package opossum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocSegmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AllocSegmentReq) Reset() {
	*x = AllocSegmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocSegmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocSegmentReq) ProtoMessage() {}

func (x *AllocSegmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocSegmentReq.ProtoReflect.Descriptor instead.
func (*AllocSegmentReq) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{0}
}

func (x *AllocSegmentReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AllocSegmentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *AllocSegmentResp) Reset() {
	*x = AllocSegmentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocSegmentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocSegmentResp) ProtoMessage() {}

func (x *AllocSegmentResp) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocSegmentResp.ProtoReflect.Descriptor instead.
func (*AllocSegmentResp) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{1}
}

func (x *AllocSegmentResp) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AllocSegmentResp) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type GetSnowflakesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetSnowflakesReq) Reset() {
	*x = GetSnowflakesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnowflakesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnowflakesReq) ProtoMessage() {}

func (x *GetSnowflakesReq) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnowflakesReq.ProtoReflect.Descriptor instead.
func (*GetSnowflakesReq) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{2}
}

func (x *GetSnowflakesReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetSnowflakesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetSnowflakesResp) Reset() {
	*x = GetSnowflakesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnowflakesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnowflakesResp) ProtoMessage() {}

func (x *GetSnowflakesResp) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnowflakesResp.ProtoReflect.Descriptor instead.
func (*GetSnowflakesResp) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{3}
}

func (x *GetSnowflakesResp) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_opossum_proto protoreflect.FileDescriptor

var file_opossum_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x22, 0x23, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x6f,
	0x63, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3a, 0x0a,
	0x10, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c,
	0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x32, 0x9a, 0x01, 0x0a, 0x07, 0x4f,
	0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x12, 0x45, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d,
	0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x73, 0x12, 0x19,
	0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77,
	0x66, 0x6c, 0x61, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x4f, 0x70, 0x6f, 0x73,
	0x73, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x73, 0x74, 0x6c, 0x61, 0x73, 0x63, 0x6f, 0x72,
	0x70, 0x69, 0x6f, 0x6e, 0x2f, 0x6f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x6f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_opossum_proto_rawDescOnce sync.Once
	file_opossum_proto_rawDescData = file_opossum_proto_rawDesc
)

func file_opossum_proto_rawDescGZIP() []byte {
	file_opossum_proto_rawDescOnce.Do(func() {
		file_opossum_proto_rawDescData = protoimpl.X.CompressGZIP(file_opossum_proto_rawDescData)
	})
	return file_opossum_proto_rawDescData
}

var file_opossum_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_opossum_proto_goTypes = []interface{}{
	(*AllocSegmentReq)(nil),   // 0: Opossum.AllocSegmentReq
	(*AllocSegmentResp)(nil),  // 1: Opossum.AllocSegmentResp
	(*GetSnowflakesReq)(nil),  // 2: Opossum.GetSnowflakesReq
	(*GetSnowflakesResp)(nil), // 3: Opossum.GetSnowflakesResp
}
var file_opossum_proto_depIdxs = []int32{
	0, // 0: Opossum.Opossum.AllocSegment:input_type -> Opossum.AllocSegmentReq
	2, // 1: Opossum.Opossum.GetSnowflakes:input_type -> Opossum.GetSnowflakesReq
	1, // 2: Opossum.Opossum.AllocSegment:output_type -> Opossum.AllocSegmentResp
	3, // 3: Opossum.Opossum.GetSnowflakes:output_type -> Opossum.GetSnowflakesResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opossum_proto_init() }
func file_opossum_proto_init() {
	if File_opossum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opossum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocSegmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocSegmentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnowflakesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnowflakesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opossum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opossum_proto_goTypes,
		DependencyIndexes: file_opossum_proto_depIdxs,
		MessageInfos:      file_opossum_proto_msgTypes,
	}.Build()
	File_opossum_proto = out.File
	file_opossum_proto_rawDesc = nil
	file_opossum_proto_goTypes = nil
	file_opossum_proto_depIdxs = nil
}
