// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.36.0
// source: opossum.proto

package opossum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpossumClient is the client API for Opossum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpossumClient interface {
	GetSegment(ctx context.Context, in *GetSegmentIdReq, opts ...grpc.CallOption) (*GetSegmentIdResp, error)
	GetSnowflake(ctx context.Context, in *GetSnowflakeIdReq, opts ...grpc.CallOption) (*GetSnowflakeIdResp, error)
	DecodeSnowflake(ctx context.Context, in *DecodeSnowflakeIdReq, opts ...grpc.CallOption) (*DecodeSnowflakeIdResp, error)
}

type opossumClient struct {
	cc grpc.ClientConnInterface
}

func NewOpossumClient(cc grpc.ClientConnInterface) OpossumClient {
	return &opossumClient{cc}
}

func (c *opossumClient) GetSegment(ctx context.Context, in *GetSegmentIdReq, opts ...grpc.CallOption) (*GetSegmentIdResp, error) {
	out := new(GetSegmentIdResp)
	err := c.cc.Invoke(ctx, "/Opossum.opossum/GetSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opossumClient) GetSnowflake(ctx context.Context, in *GetSnowflakeIdReq, opts ...grpc.CallOption) (*GetSnowflakeIdResp, error) {
	out := new(GetSnowflakeIdResp)
	err := c.cc.Invoke(ctx, "/Opossum.opossum/GetSnowflake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opossumClient) DecodeSnowflake(ctx context.Context, in *DecodeSnowflakeIdReq, opts ...grpc.CallOption) (*DecodeSnowflakeIdResp, error) {
	out := new(DecodeSnowflakeIdResp)
	err := c.cc.Invoke(ctx, "/Opossum.opossum/DecodeSnowflake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpossumServer is the server API for Opossum service.
// All implementations must embed UnimplementedOpossumServer
// for forward compatibility
type OpossumServer interface {
	GetSegment(context.Context, *GetSegmentIdReq) (*GetSegmentIdResp, error)
	GetSnowflake(context.Context, *GetSnowflakeIdReq) (*GetSnowflakeIdResp, error)
	DecodeSnowflake(context.Context, *DecodeSnowflakeIdReq) (*DecodeSnowflakeIdResp, error)
	mustEmbedUnimplementedOpossumServer()
}

// UnimplementedOpossumServer must be embedded to have forward compatible implementations.
type UnimplementedOpossumServer struct {
}

func (UnimplementedOpossumServer) GetSegment(context.Context, *GetSegmentIdReq) (*GetSegmentIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSegment not implemented")
}
func (UnimplementedOpossumServer) GetSnowflake(context.Context, *GetSnowflakeIdReq) (*GetSnowflakeIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnowflake not implemented")
}
func (UnimplementedOpossumServer) DecodeSnowflake(context.Context, *DecodeSnowflakeIdReq) (*DecodeSnowflakeIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeSnowflake not implemented")
}
func (UnimplementedOpossumServer) mustEmbedUnimplementedOpossumServer() {}

// UnsafeOpossumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpossumServer will
// result in compilation errors.
type UnsafeOpossumServer interface {
	mustEmbedUnimplementedOpossumServer()
}

func RegisterOpossumServer(s grpc.ServiceRegistrar, srv OpossumServer) {
	s.RegisterService(&Opossum_ServiceDesc, srv)
}

func _Opossum_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpossumServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Opossum.opossum/GetSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpossumServer).GetSegment(ctx, req.(*GetSegmentIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Opossum_GetSnowflake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnowflakeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpossumServer).GetSnowflake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Opossum.opossum/GetSnowflake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpossumServer).GetSnowflake(ctx, req.(*GetSnowflakeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Opossum_DecodeSnowflake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeSnowflakeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpossumServer).DecodeSnowflake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Opossum.opossum/DecodeSnowflake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpossumServer).DecodeSnowflake(ctx, req.(*DecodeSnowflakeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Opossum_ServiceDesc is the grpc.ServiceDesc for Opossum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Opossum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Opossum.opossum",
	HandlerType: (*OpossumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSegment",
			Handler:    _Opossum_GetSegment_Handler,
		},
		{
			MethodName: "GetSnowflake",
			Handler:    _Opossum_GetSnowflake_Handler,
		},
		{
			MethodName: "DecodeSnowflake",
			Handler:    _Opossum_DecodeSnowflake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opossum.proto",
}
