// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.0
// source: opossum.proto

package opossum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Opossum_AllocSegment_FullMethodName  = "/Opossum.Opossum/AllocSegment"
	Opossum_GetSnowflakes_FullMethodName = "/Opossum.Opossum/GetSnowflakes"
)

// OpossumClient is the client API for Opossum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpossumClient interface {
	AllocSegment(ctx context.Context, in *AllocSegmentReq, opts ...grpc.CallOption) (*AllocSegmentResp, error)
	GetSnowflakes(ctx context.Context, in *GetSnowflakesReq, opts ...grpc.CallOption) (*GetSnowflakesResp, error)
}

type opossumClient struct {
	cc grpc.ClientConnInterface
}

func NewOpossumClient(cc grpc.ClientConnInterface) OpossumClient {
	return &opossumClient{cc}
}

func (c *opossumClient) AllocSegment(ctx context.Context, in *AllocSegmentReq, opts ...grpc.CallOption) (*AllocSegmentResp, error) {
	out := new(AllocSegmentResp)
	err := c.cc.Invoke(ctx, Opossum_AllocSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opossumClient) GetSnowflakes(ctx context.Context, in *GetSnowflakesReq, opts ...grpc.CallOption) (*GetSnowflakesResp, error) {
	out := new(GetSnowflakesResp)
	err := c.cc.Invoke(ctx, Opossum_GetSnowflakes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpossumServer is the server API for Opossum service.
// All implementations must embed UnimplementedOpossumServer
// for forward compatibility
type OpossumServer interface {
	AllocSegment(context.Context, *AllocSegmentReq) (*AllocSegmentResp, error)
	GetSnowflakes(context.Context, *GetSnowflakesReq) (*GetSnowflakesResp, error)
	mustEmbedUnimplementedOpossumServer()
}

// UnimplementedOpossumServer must be embedded to have forward compatible implementations.
type UnimplementedOpossumServer struct {
}

func (UnimplementedOpossumServer) AllocSegment(context.Context, *AllocSegmentReq) (*AllocSegmentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocSegment not implemented")
}
func (UnimplementedOpossumServer) GetSnowflakes(context.Context, *GetSnowflakesReq) (*GetSnowflakesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnowflakes not implemented")
}
func (UnimplementedOpossumServer) mustEmbedUnimplementedOpossumServer() {}

// UnsafeOpossumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpossumServer will
// result in compilation errors.
type UnsafeOpossumServer interface {
	mustEmbedUnimplementedOpossumServer()
}

func RegisterOpossumServer(s grpc.ServiceRegistrar, srv OpossumServer) {
	s.RegisterService(&Opossum_ServiceDesc, srv)
}

func _Opossum_AllocSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocSegmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpossumServer).AllocSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Opossum_AllocSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpossumServer).AllocSegment(ctx, req.(*AllocSegmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Opossum_GetSnowflakes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnowflakesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpossumServer).GetSnowflakes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Opossum_GetSnowflakes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpossumServer).GetSnowflakes(ctx, req.(*GetSnowflakesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Opossum_ServiceDesc is the grpc.ServiceDesc for Opossum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Opossum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Opossum.Opossum",
	HandlerType: (*OpossumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocSegment",
			Handler:    _Opossum_AllocSegment_Handler,
		},
		{
			MethodName: "GetSnowflakes",
			Handler:    _Opossum_GetSnowflakes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opossum.proto",
}
