// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.36.0
// source: opossum.proto

package opossum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSegmentIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetSegmentIdReq) Reset() {
	*x = GetSegmentIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSegmentIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentIdReq) ProtoMessage() {}

func (x *GetSegmentIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentIdReq.ProtoReflect.Descriptor instead.
func (*GetSegmentIdReq) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{0}
}

func (x *GetSegmentIdReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSegmentIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSegmentIdResp) Reset() {
	*x = GetSegmentIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSegmentIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentIdResp) ProtoMessage() {}

func (x *GetSegmentIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentIdResp.ProtoReflect.Descriptor instead.
func (*GetSegmentIdResp) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{1}
}

func (x *GetSegmentIdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSnowflakeIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSnowflakeIdReq) Reset() {
	*x = GetSnowflakeIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnowflakeIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnowflakeIdReq) ProtoMessage() {}

func (x *GetSnowflakeIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnowflakeIdReq.ProtoReflect.Descriptor instead.
func (*GetSnowflakeIdReq) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{2}
}

type GetSnowflakeIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSnowflakeIdResp) Reset() {
	*x = GetSnowflakeIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnowflakeIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnowflakeIdResp) ProtoMessage() {}

func (x *GetSnowflakeIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnowflakeIdResp.ProtoReflect.Descriptor instead.
func (*GetSnowflakeIdResp) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{3}
}

func (x *GetSnowflakeIdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DecodeSnowflakeIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DecodeSnowflakeIdReq) Reset() {
	*x = DecodeSnowflakeIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeSnowflakeIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeSnowflakeIdReq) ProtoMessage() {}

func (x *DecodeSnowflakeIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeSnowflakeIdReq.ProtoReflect.Descriptor instead.
func (*DecodeSnowflakeIdReq) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{4}
}

func (x *DecodeSnowflakeIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DecodeSnowflakeIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp  int64 `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	WorkerId   int64 `protobuf:"varint,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
	SequenceId int64 `protobuf:"varint,3,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
}

func (x *DecodeSnowflakeIdResp) Reset() {
	*x = DecodeSnowflakeIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opossum_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeSnowflakeIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeSnowflakeIdResp) ProtoMessage() {}

func (x *DecodeSnowflakeIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_opossum_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeSnowflakeIdResp.ProtoReflect.Descriptor instead.
func (*DecodeSnowflakeIdResp) Descriptor() ([]byte, []int) {
	return file_opossum_proto_rawDescGZIP(), []int{5}
}

func (x *DecodeSnowflakeIdResp) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *DecodeSnowflakeIdResp) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *DecodeSnowflakeIdResp) GetSequenceId() int64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

var File_opossum_proto protoreflect.FileDescriptor

var file_opossum_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x22, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14,
	0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x15, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x6e,
	0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x32, 0xed, 0x01, 0x0a, 0x07, 0x6f, 0x70, 0x6f, 0x73,
	0x73, 0x75, 0x6d, 0x12, 0x43, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x18, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x4f, 0x70,
	0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53,
	0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x12, 0x1a, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73,
	0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x12, 0x1d, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d,
	0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x2e,
	0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x73, 0x74, 0x6c, 0x61, 0x73, 0x63, 0x6f, 0x72,
	0x70, 0x69, 0x6f, 0x6e, 0x2f, 0x4f, 0x70, 0x6f, 0x73, 0x73, 0x75, 0x6d, 0x3b, 0x6f, 0x70, 0x6f,
	0x73, 0x73, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_opossum_proto_rawDescOnce sync.Once
	file_opossum_proto_rawDescData = file_opossum_proto_rawDesc
)

func file_opossum_proto_rawDescGZIP() []byte {
	file_opossum_proto_rawDescOnce.Do(func() {
		file_opossum_proto_rawDescData = protoimpl.X.CompressGZIP(file_opossum_proto_rawDescData)
	})
	return file_opossum_proto_rawDescData
}

var file_opossum_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_opossum_proto_goTypes = []interface{}{
	(*GetSegmentIdReq)(nil),       // 0: Opossum.GetSegmentIdReq
	(*GetSegmentIdResp)(nil),      // 1: Opossum.GetSegmentIdResp
	(*GetSnowflakeIdReq)(nil),     // 2: Opossum.GetSnowflakeIdReq
	(*GetSnowflakeIdResp)(nil),    // 3: Opossum.GetSnowflakeIdResp
	(*DecodeSnowflakeIdReq)(nil),  // 4: Opossum.DecodeSnowflakeIdReq
	(*DecodeSnowflakeIdResp)(nil), // 5: Opossum.DecodeSnowflakeIdResp
}
var file_opossum_proto_depIdxs = []int32{
	0, // 0: Opossum.opossum.GetSegment:input_type -> Opossum.GetSegmentIdReq
	2, // 1: Opossum.opossum.GetSnowflake:input_type -> Opossum.GetSnowflakeIdReq
	4, // 2: Opossum.opossum.DecodeSnowflake:input_type -> Opossum.DecodeSnowflakeIdReq
	1, // 3: Opossum.opossum.GetSegment:output_type -> Opossum.GetSegmentIdResp
	3, // 4: Opossum.opossum.GetSnowflake:output_type -> Opossum.GetSnowflakeIdResp
	5, // 5: Opossum.opossum.DecodeSnowflake:output_type -> Opossum.DecodeSnowflakeIdResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opossum_proto_init() }
func file_opossum_proto_init() {
	if File_opossum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opossum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSegmentIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSegmentIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnowflakeIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnowflakeIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeSnowflakeIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opossum_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeSnowflakeIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opossum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opossum_proto_goTypes,
		DependencyIndexes: file_opossum_proto_depIdxs,
		MessageInfos:      file_opossum_proto_msgTypes,
	}.Build()
	File_opossum_proto = out.File
	file_opossum_proto_rawDesc = nil
	file_opossum_proto_goTypes = nil
	file_opossum_proto_depIdxs = nil
}
